# Generated by Django 3.2.7 on 2021-10-08 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.lista')),
            ],
        ),
    ]
